twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['tailwind_2_layout.html.twig', 'forms/form-themes.html.twig']
    globals:
        site_name: '%env(SITE_NAME)%'

when@test:
    twig:
        strict_variables: true
