<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20220613134526 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Initial DB schema';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE "user" (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255), enabled BOOLEAN NOT NULL, totp_secret VARCHAR(255) DEFAULT NULL, totp_enabled BOOLEAN DEFAULT false NOT NULL)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AD8A54A9E7927C74 ON "user" (email)');

        // admin_users
        $this->addSql('INSERT INTO "user" ("id", "email", "roles", "password", "enabled") VALUES (1, \'test@example.com\', \'["ROLE_USER"]\', \'$2y$13$Dv4EUU1hhB9AawNM4iKIEutXAj6oFmc8y5cRWh4zeCQX05F2audci\', true)');
        $this->addSql('ALTER TABLE "user" ALTER COLUMN id RESTART WITH 2');

        // Admin password reset
        $this->addSql('CREATE TABLE user_reset_password_request (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id INT NOT NULL, selector VARCHAR(20) NOT NULL, hashed_token VARCHAR(100) NOT NULL, requested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL)');
        $this->addSql('CREATE INDEX IDX_93470FAAA76ED395 ON user_reset_password_request (user_id)');
        $this->addSql('COMMENT ON COLUMN user_reset_password_request.requested_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN user_reset_password_request.expires_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE user_reset_password_request ADD CONSTRAINT FK_7CE748AA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE "user_reset_password_request"');
        $this->addSql('DROP TABLE "user" CASCADE');
    }
}
